version: '2'
services:
    php:
        restart: always
        build: .
        ports:
            - $PORT:80
        volumes:
            - ./php:/var/www/html
            - $PROJECT_DIR:/projects
        environment:
            - USERID=$USERID
            - GROUPID=$GROUPID
