version: '2'
services:
    php:
        restart: always
        image: php:5.6-apache
        ports: 
            - $PORT:80
        volumes:
            - ./php:/var/www/html
            - $PROJECT_DIR:/projects
        logging:
          driver: syslog
          options:
              syslog-address: $SYSLOG_ADDRESS
              tag: "HABITEO_DOCKER_LOG-chrome"
